[effect78]
Name = "EFFECT_SPANGLE_ORANGE2"
Health = 1
GenerationType = 1
GenerationAccelXYRange = [32,32]
GenerationAccelZRange = [-32,32]
GenerationKindRange = [1,1]
ElementsCount = 1
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
[effectElement115]
Name = "ARENA_EFFECT_RED_SPRITE"
DrawClass = 2
MoveType = 0
Unanimated = 0
Lifespan = [3,3]
AnimationId = 852
SpriteSize = [90,91]
RenderFlags = 1
SpriteSpeed = [700,700]
AnimateOnFloor = true
Unshaded = true
Transparant = 3
MovementFlags = 0
SizeChange = 0
fallAcceleration = 0
InertiaFloor = 0
InertiaAir = 0
SubeffectModel = 0
SubeffectDelay = 0
Movable = false
Impacts = false
TransformModel = 0
LightRadius = 0
LightIntensity = 0
LightFlags = 0
AffectedByWind = 0
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
[effectElement116]
Name = "ARENA_EFFECT_BLUE_SPRITE"
DrawClass = 2
MoveType = 0
Unanimated = 0
Lifespan = [3,3]
AnimationId = 853
SpriteSize = [90,91]
RenderFlags = 1
SpriteSpeed = [700,700]
AnimateOnFloor = true
Unshaded = true
Transparant = 3
MovementFlags = 0
SizeChange = 0
fallAcceleration = 0
InertiaFloor = 0
InertiaAir = 0
SubeffectModel = 0
SubeffectDelay = 0
Movable = false
Impacts = false
TransformModel = 0
LightRadius = 0
LightIntensity = 0
LightFlags = 0
AffectedByWind = 0
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
[effectElement117]
Name = "ARENA_EFFECT_GREEN_SPRITE"
DrawClass = 2
MoveType = 0
Unanimated = 0
Lifespan = [3,3]
AnimationId = 854
SpriteSize = [90,91]
RenderFlags = 1
SpriteSpeed = [700,700]
AnimateOnFloor = true
Unshaded = true
Transparant = 3
MovementFlags = 0
SizeChange = 0
fallAcceleration = 0
InertiaFloor = 0
InertiaAir = 0
SubeffectModel = 0
SubeffectDelay = 0
Movable = false
Impacts = false
TransformModel = 0
LightRadius = 0
LightIntensity = 0
LightFlags = 0
AffectedByWind = 0
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################
[effectElement118]
Name = "ARENA_EFFECT_YELLOW_SPRITE"
DrawClass = 2
MoveType = 0
Unanimated = 0
Lifespan = [3,3]
AnimationId = 855
SpriteSize = [90,91]
RenderFlags = 1
SpriteSpeed = [700,700]
AnimateOnFloor = true
Unshaded = true
Transparant = 3
MovementFlags = 0
SizeChange = 0
fallAcceleration = 0
InertiaFloor = 0
InertiaAir = 0
SubeffectModel = 0
SubeffectDelay = 0
Movable = false
Impacts = false
TransformModel = 0
LightRadius = 0
LightIntensity = 0
LightFlags = 0
AffectedByWind = 0
########################################################################################################################################################
########################################################################################################################################################
########################################################################################################################################################